// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0BPk53r5OkVXHqHGtgfJoTPJMHMuQko',
    appId: '1:986323670638:web:e4a66601038518c4cbb87f',
    messagingSenderId: '986323670638',
    projectId: 'app-control-residentes-343e8',
    authDomain: 'app-control-residentes-343e8.firebaseapp.com',
    storageBucket: 'app-control-residentes-343e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38y7LH9DxZjQzTYIFvKocNxOSAU06vJ8',
    appId: '1:986323670638:android:3c4895546aad9163cbb87f',
    messagingSenderId: '986323670638',
    projectId: 'app-control-residentes-343e8',
    storageBucket: 'app-control-residentes-343e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHi5KO7kppVg7qWPcjpTO3OVX3OZnEaM',
    appId: '1:986323670638:ios:a56c4c6c7e8b3ae7cbb87f',
    messagingSenderId: '986323670638',
    projectId: 'app-control-residentes-343e8',
    storageBucket: 'app-control-residentes-343e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppControlResidentes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHi5KO7kppVg7qWPcjpTO3OVX3OZnEaM',
    appId: '1:986323670638:ios:a56c4c6c7e8b3ae7cbb87f',
    messagingSenderId: '986323670638',
    projectId: 'app-control-residentes-343e8',
    storageBucket: 'app-control-residentes-343e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppControlResidentes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL0BPk53r5OkVXHqHGtgfJoTPJMHMuQko',
    appId: '1:986323670638:web:fa2cdaed1404b98bcbb87f',
    messagingSenderId: '986323670638',
    projectId: 'app-control-residentes-343e8',
    authDomain: 'app-control-residentes-343e8.firebaseapp.com',
    storageBucket: 'app-control-residentes-343e8.firebasestorage.app',
  );
}
